name: on PR merged

on:
  pull_request_target:
    types: [ closed ]
    branches: [ main ]

#  push:
#    branches: [main]
jobs:
  if_release_merged:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.export_version.VERSION }}
    steps:
      - run: echo "The PR was merged ${{github.event.pull_request.head.ref}}"
      - run: echo "BRANCH_NAME=${{github.event.pull_request.head.ref}}" >> $GITHUB_ENV
#       - run: echo "test=$GITHUB_REF"
      - id: export_version
        run: echo "VERSION=${BRANCH_NAME/release\/}" # >> "$GITHUB_OUTPUT"
#       - run: echo "VERSION=${{github.event.pull_request.head.ref}}"
  job2:
    runs-on: ubuntu-latest
    needs: if_release_merged
    steps:
      - env:
          VERSION: ${{needs.if_release_merged.outputs.version}}
        run: echo "$VERSION"

