name: Prerelease 배포

on:
  push:
    branches:
      - 'release/*'
    paths:
      - 'src/**'

jobs:
  publish-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/.package-hash-for-cache') }}
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      # npm version
      - run: git config --global user.email "github-action[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-action[bot]"
      - run: npm version prerelease --preid=rc -m "prerelease v%s"

      # publish
      - run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Push commit # publish 성공한 경우만 새로운 태그 push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
