name: Tester4

on:
  workflow_dispatch:
    inputs:
      branchname:
        description: 'test'
        required: true

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - id: stoppable
        name: Stoppable
        run: |
          if [[ "${{inputs.branchname}}" = "error" ]]; then
            echo "::error:: 오류코드"
          else
            echo "::set-output name=should_run::true"
          fi
      - name: Next Step
        if: ${{ steps.stoppable.outputs.should_run == 'true' }}
        run: echo hello
    
