name: Test 3

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'branch'
        required: true
        default: 'temp'

jobs:
  if-release-merged:
    name: '조건 체크 / node_module 등 준비'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.branch-name}}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/.package-hash-for-cache') }}
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: echo "BRANCH_NAME=test-branch-name" >> $GITHUB_ENV
      - run: echo "VERSION=minor" >> $GITHUB_ENV
    outputs:
      branch-name: ${{ env.BRANCH_NAME }}
      version: ${{ env.VERSION }}

  publish-gpr:
    name: '정식 배포'
    needs: if-release-merged
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ needs.if-release-merged.outputs.branch-name }}
      VERSION: ${{ needs.if-release-merged.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.branch-name}}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/.package-hash-for-cache') }}
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: git config --global user.email "github-action[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-action[bot]"
      - run: npm version $VERSION -m "v%s - published by ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"

      # publish 성공한 경우만 새로운 태그 push
      - name: Push commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{inputs.branch-name}}
          tags: true
  create-release:
    needs: [ if-release-merged, publish-gpr ]
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.if-release-merged.outputs.version }}
    steps:
      # release 생성
      - name: Create Release
        id: create_release
        run: echo "create release ${{github.server_url}}/${{github.repository}}/tree/v${{env.VERSION}}/docs/README.md"

  # 머지된 브랜치 삭제
  delete-merged-branch:
    needs: [ if-release-merged, publish-gpr ]
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      BRANCH_NAME: ${{ needs.if-release-merged.outputs.branch-name }}
    steps:
      - name: Delete merged branches
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ env.BRANCH_NAME }}

  # rc 버전 태그 삭제
  delete-prerelease-tags:
    needs: [ if-release-merged, publish-gpr ]
    runs-on: ubuntu-latest
    steps:
      - run: git fetch --tags
      - run: if [[ $(git tag -l "*-rc.*") ]]; then git push origin -d $(git tag -l "*-rc.*"); fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git tag -d $(git tag -l)

  # 신규 patch 버전 브랜치 생성
  create-new-branch:
    needs: [ if-release-merged, publish-gpr ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.branch-name}}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/.package-hash-for-cache') }}
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: git config --global user.email "github-action[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-action[bot]"
      - run: npm version prerelease --preid=rc -m "v%s - created by ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
      - name: get new branch name
        run: echo NEW_BRANCH_NAME=release/$(npm pkg get version --workspaces=false | tr -d \") | sed 's/-rc.*//' >> $GITHUB_ENV
      - name: checkout new version branch
        run: git checkout -b $NEW_BRANCH_NAME
      - name: Push New Version Branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.NEW_BRANCH_NAME }}
          tags: true

  delete-prerelease-packages:
    needs: [ if-release-merged, publish-gpr ]
    runs-on: ubuntu-latest
    steps:
      # rc 패키지 삭제
      - uses: actions/delete-package-versions@v4
        with:
          owner: ${{ github.repository_owner }}
          package-name: 'pkg-test'
          package-type: 'npm'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 0
          delete-only-pre-release-versions: "true"
