name: Tester

on:
  workflow_dispatch:
    inputs:
      branchname:
        description: 'test'
        required: true
        default: 'release/5.1.0'

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The PR was merged ${{inputs.branchname}}"
      - run: echo "BRANCH_NAME=${{inputs.branchname}}" >> $GITHUB_ENV
      - run: echo "test=$GITHUB_REF"
      - id: export_version
        run: echo "VERSION=${BRANCH_NAME/release\/}" # >> "$GITHUB_OUTPUT"
      - run: echo "VERSION=${{inputs.branchname}}"
    outputs:
      BRANCH_NAME_TEST: ${{ env.BRANCH_NAME }}
  job_2:
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.job_1.outputs.BRANCH_NAME_TEST }}"
    
