name: Tester4

on:
  workflow_dispatch:
    inputs:
      branchname:
        description: 'test'
        required: true

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Stoppable
        run: |
          if [[ "${{inputs.branchname}}" = "error" ]]; then
            echo "::error:: 오류코드 1"
            exit 1
          elif [[ "${{inputs.branchname}}" = "warn" ]]; then
            echo "::warn:: 오류코드 0"
            exit 0
          fi
      - name: Next Step
        run: echo hello
    
